// <auto-generated />
using System;
using Invoice.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice.Migrations
{
    [DbContext(typeof(InvoiceDBContext))]
    [Migration("20251102141120_Create the ItemInterval table with data")]
    partial class CreatetheItemIntervaltablewithdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoice.Model.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("bank_name");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("bank", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.BankDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("account_number");

                    b.Property<int>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("bank_id");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("isfc_code");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("bank_detail", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_2");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_3");

                    b.Property<string>("City")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("country");

                    b.Property<string>("GSTNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("gst_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("PANNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("varchar");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("phone_no");

                    b.Property<string>("State")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_2");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_3");

                    b.Property<string>("CessNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("cess_no");

                    b.Property<string>("City")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("city");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("country");

                    b.Property<string>("GSTNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("gst_no");

                    b.Property<string>("InvoiceFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("invoice_format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("PANNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("varchar");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("phone_no");

                    b.Property<string>("State")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("state");

                    b.Property<string>("TaxCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("tax_category");

                    b.Property<double>("TripRate")
                        .HasColumnType("float")
                        .HasColumnName("trip_rate");

                    b.Property<string>("Zip")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("DriverMobile")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("driver_mobile");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("driver_name");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("license_no");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("driver", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.FinancialYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime")
                        .HasColumnName("from_date");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime")
                        .HasColumnName("to_date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("financial_year", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money")
                        .HasColumnName("amount");

                    b.Property<int>("BankDetailId")
                        .HasColumnType("int")
                        .HasColumnName("bank_detail_id");

                    b.Property<decimal?>("CGST")
                        .HasColumnType("money")
                        .HasColumnName("c_gst");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int")
                        .HasColumnName("financial_year_id");

                    b.Property<decimal?>("IGST")
                        .HasColumnType("money")
                        .HasColumnName("i_gst");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("invoice_no");

                    b.Property<decimal?>("SGST")
                        .HasColumnType("money")
                        .HasColumnName("s_gst");

                    b.Property<int?>("StartingKM")
                        .HasColumnType("int")
                        .HasColumnName("starting_KM");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime")
                        .HasColumnName("starting_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("invoice_status");

                    b.Property<decimal?>("Total")
                        .HasColumnType("money")
                        .HasColumnName("total");

                    b.Property<int?>("VehicleDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankDetailId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("VehicleDetailId");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountBeforeTax")
                        .HasColumnType("money")
                        .HasColumnName("amount_before_tax");

                    b.Property<decimal>("CGST")
                        .HasColumnType("money")
                        .HasColumnName("cgst");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<decimal>("IGST")
                        .HasColumnType("money")
                        .HasColumnName("igst");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int?>("ItemId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("money")
                        .HasColumnName("rate");

                    b.Property<decimal>("SGST")
                        .HasColumnType("money")
                        .HasColumnName("sgst");

                    b.Property<int?>("VoucherDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ItemId");

                    b.ToTable("invoice_detail", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.ItemInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Interval")
                        .HasColumnType("int")
                        .HasColumnName("interval");

                    b.Property<string>("IntervalName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("interval_name");

                    b.HasKey("Id");

                    b.ToTable("item_interval", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.ItemMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AppliedGST")
                        .HasColumnType("bit")
                        .HasColumnName("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("IntervalId")
                        .HasColumnType("int")
                        .HasColumnName("internal_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("item_quantity");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("money")
                        .HasColumnName("item_rate");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_unit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IntervalId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.PaymentReceived", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CGST")
                        .HasColumnType("money")
                        .HasColumnName("c_gst");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int")
                        .HasColumnName("financial_year_id");

                    b.Property<decimal>("IGST")
                        .HasColumnType("money")
                        .HasColumnName("i_gst");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("money")
                        .HasColumnName("payment_amount");

                    b.Property<decimal>("ReceivedAmount")
                        .HasColumnType("money")
                        .HasColumnName("receive_amount");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("reference_number");

                    b.Property<DateTime>("ReveivedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("receive_date");

                    b.Property<decimal>("SGST")
                        .HasColumnType("money")
                        .HasColumnName("s_gst");

                    b.Property<decimal>("TDS")
                        .HasColumnType("money")
                        .HasColumnName("tds");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("payment_received", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.VehicleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("registration_number");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_detail", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.VehicleRateConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("configuration_type");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("VehicleId");

                    b.ToTable("vahicle_rate_configuration", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.VoucherDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("amount");

                    b.Property<int?>("InvoiceDetailId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_detail_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDetailId")
                        .IsUnique()
                        .HasFilter("[invoice_detail_id] IS NOT NULL");

                    b.HasIndex("ItemId");

                    b.HasIndex("VoucherId");

                    b.ToTable("voucher_detail", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.VoucherMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<string>("DropLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("drop_location");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int")
                        .HasColumnName("financial_year_id");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("from_date");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pickup_location");

                    b.Property<int?>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("to_date");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("voucher_date");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voucherStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("voucher_status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("voucher_master", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Bank", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Banks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BANK_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.BankDetail", b =>
                {
                    b.HasOne("Invoice.Model.Bank", "Bank")
                        .WithMany("BankDetail")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BANK_DETAIL_BANK");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Invoice.Model.Customer", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CUSTOMER_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.Driver", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Drivers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DRIVER_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.FinancialYear", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("FinancialYears")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FINANCIAL_YEAR_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.Invoice", b =>
                {
                    b.HasOne("Invoice.Model.BankDetail", "BankDetail")
                        .WithMany("Invoices")
                        .HasForeignKey("BankDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_BANK_DETAIL_ID");

                    b.HasOne("Invoice.Model.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_CUSTOMER_ID");

                    b.HasOne("Invoice.Model.Driver", null)
                        .WithMany("Invoices")
                        .HasForeignKey("DriverId");

                    b.HasOne("Invoice.Model.FinancialYear", "FinancialYear")
                        .WithMany("Invoices")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_FINANCIAL_YEAR");

                    b.HasOne("Invoice.Model.VehicleDetail", null)
                        .WithMany("Invoices")
                        .HasForeignKey("VehicleDetailId");

                    b.Navigation("BankDetail");

                    b.Navigation("Customer");

                    b.Navigation("FinancialYear");
                });

            modelBuilder.Entity("Invoice.Model.InvoiceDetail", b =>
                {
                    b.HasOne("Invoice.Model.Invoice", "Invoice")
                        .WithMany("InvoiceDetail")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_INVOICE_DETAIL");

                    b.HasOne("Invoice.Model.ItemMaster", "Item")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_DETAIL_ITEM");

                    b.Navigation("Invoice");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Invoice.Model.ItemMaster", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Items")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ITEM_COMPANY");

                    b.HasOne("Invoice.Model.ItemInterval", "Interval")
                        .WithMany("Items")
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ITEM_INTERVAL");

                    b.Navigation("Company");

                    b.Navigation("Interval");
                });

            modelBuilder.Entity("Invoice.Model.PaymentReceived", b =>
                {
                    b.HasOne("Invoice.Model.FinancialYear", "FinancialYear")
                        .WithMany("Payments")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FINANCIAL_YEAR_PAYMENT");

                    b.HasOne("Invoice.Model.Invoice", "Invoice")
                        .WithMany("PaymentReceived")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_PAYMENT");

                    b.Navigation("FinancialYear");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Invoice.Model.Vehicle", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.VehicleDetail", b =>
                {
                    b.HasOne("Invoice.Model.Vehicle", "Vehicle")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_DETAIL_VEHICLE");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Invoice.Model.VehicleRateConfiguration", b =>
                {
                    b.HasOne("Invoice.Model.Customer", "Customer")
                        .WithMany("RateConfigurations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VEHICLE_CUSTOER_RATE_DETAIL");

                    b.HasOne("Invoice.Model.ItemMaster", "ItemMaster")
                        .WithMany("VehicleRates")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_RATES_ITEM_DETAIL");

                    b.HasOne("Invoice.Model.Vehicle", "Vehicle")
                        .WithMany("VehicleRates")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_RATES_VEHICLE_DETAIL");

                    b.Navigation("Customer");

                    b.Navigation("ItemMaster");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Invoice.Model.VoucherDetail", b =>
                {
                    b.HasOne("Invoice.Model.InvoiceDetail", "InvoiceDetail")
                        .WithOne("VoucherDetail")
                        .HasForeignKey("Invoice.Model.VoucherDetail", "InvoiceDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VOUCHER_DETAIL_INVOICE_DETAIL");

                    b.HasOne("Invoice.Model.ItemMaster", "Item")
                        .WithMany("VoucherDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VOUCHER_DETAIL_ITEM");

                    b.HasOne("Invoice.Model.VoucherMaster", "Voucher")
                        .WithMany("Details")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VOUCHER_DETAIL_VOUCHER_MASTER");

                    b.Navigation("InvoiceDetail");

                    b.Navigation("Item");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Invoice.Model.VoucherMaster", b =>
                {
                    b.HasOne("Invoice.Model.Customer", "Customer")
                        .WithMany("Vouchers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VOUCHER_CUSTOMER");

                    b.HasOne("Invoice.Model.Driver", "Driver")
                        .WithMany("Vouchers")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VOUCHER_DRIVER");

                    b.HasOne("Invoice.Model.FinancialYear", "FinancialYear")
                        .WithMany("Vouchers")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VOUCHER_FINANCIAL_YEAR_ID");

                    b.HasOne("Invoice.Model.Invoice", "Invoice")
                        .WithMany("Vouchers")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VOUCHER_INVOICE");

                    b.HasOne("Invoice.Model.VehicleDetail", "VehicleDetail")
                        .WithMany("Vouchers")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_VOUCHER_REGISTRATION");

                    b.HasOne("Invoice.Model.Vehicle", "Vehicle")
                        .WithMany("Vouchers")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VOUCHER_VEHICLE");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("FinancialYear");

                    b.Navigation("Invoice");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleDetail");
                });

            modelBuilder.Entity("Invoice.Model.Bank", b =>
                {
                    b.Navigation("BankDetail");
                });

            modelBuilder.Entity("Invoice.Model.BankDetail", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Invoice.Model.Company", b =>
                {
                    b.Navigation("Banks");

                    b.Navigation("Customers");

                    b.Navigation("Drivers");

                    b.Navigation("FinancialYears");

                    b.Navigation("Items");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Invoice.Model.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("RateConfigurations");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Invoice.Model.Driver", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Invoice.Model.FinancialYear", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Invoice.Model.Invoice", b =>
                {
                    b.Navigation("InvoiceDetail");

                    b.Navigation("PaymentReceived");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Invoice.Model.InvoiceDetail", b =>
                {
                    b.Navigation("VoucherDetail");
                });

            modelBuilder.Entity("Invoice.Model.ItemInterval", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Invoice.Model.ItemMaster", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("VehicleRates");

                    b.Navigation("VoucherDetails");
                });

            modelBuilder.Entity("Invoice.Model.Vehicle", b =>
                {
                    b.Navigation("VehicleRates");

                    b.Navigation("Vehicles");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Invoice.Model.VehicleDetail", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Invoice.Model.VoucherMaster", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
