// <auto-generated />
using System;
using Invoice.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice.Migrations
{
    [DbContext(typeof(InvoiceDBContext))]
    [Migration("20251004092204_Add VehicleRates entity")]
    partial class AddVehicleRatesentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoice.Model.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("bank_name");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("bank", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.BankDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("account_number");

                    b.Property<int>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("bank_id");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("isfc_code");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("bank_detail", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_2");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_3");

                    b.Property<string>("City")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("country");

                    b.Property<string>("GSTNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("gst_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("PANNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("varchar");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("phone_no");

                    b.Property<string>("State")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_2");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("address_3");

                    b.Property<string>("CessNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("cess_no");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("city");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("country");

                    b.Property<string>("GSTNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("gst_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("PANNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("varchar");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("phone_no");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("state");

                    b.Property<double>("TripRate")
                        .HasColumnType("float")
                        .HasColumnName("trip_rate");

                    b.Property<string>("Zip")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("DriverMobile")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("driver_mobile");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("driver_name");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("license_no");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("driver", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.FinancialYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime")
                        .HasColumnName("from_date");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime")
                        .HasColumnName("to_date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("financial_year", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CGST")
                        .HasColumnType("money")
                        .HasColumnName("c_gst");

                    b.Property<int?>("DriverId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int")
                        .HasColumnName("financial_year_id");

                    b.Property<decimal?>("IGST")
                        .HasColumnType("money")
                        .HasColumnName("i_gst");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("invoice_no");

                    b.Property<string>("SACCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("sac_code");

                    b.Property<decimal?>("SGST")
                        .HasColumnType("money")
                        .HasColumnName("s_gst");

                    b.Property<int?>("StartingKM")
                        .HasColumnType("int")
                        .HasColumnName("starting_KM");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime")
                        .HasColumnName("starting_time");

                    b.Property<string>("StateCode")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("state_code");

                    b.Property<decimal?>("Total")
                        .HasColumnType("money")
                        .HasColumnName("total");

                    b.Property<int?>("VehicleDetailId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_detail_id");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("VehicleDetailId");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money")
                        .HasColumnName("amount");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("money")
                        .HasColumnName("rate");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ItemId");

                    b.ToTable("invoice_detail", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.ItemMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AppliedGST")
                        .HasColumnType("bit")
                        .HasColumnName("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("item_quantity");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("money")
                        .HasColumnName("item_rate");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_unit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.VehicleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("registration_number");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_detail", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.VehicleRateConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("VehicleId");

                    b.ToTable("vahicle_rate_configuration", (string)null);
                });

            modelBuilder.Entity("Invoice.Model.Bank", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Banks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BANK_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.BankDetail", b =>
                {
                    b.HasOne("Invoice.Model.Bank", "Bank")
                        .WithMany("BankDetail")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BANK_DETAIL_BANK");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Invoice.Model.Customer", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CUSTOMER_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.Driver", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Drivers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DRIVER_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.FinancialYear", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("FinancialYears")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FINANCIAL_YEAR_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.Invoice", b =>
                {
                    b.HasOne("Invoice.Model.FinancialYear", "FinancialYear")
                        .WithMany("Invoices")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_FINANCIAL_YEAR");

                    b.HasOne("Invoice.Model.Driver", "Driver")
                        .WithMany("Invoices")
                        .HasForeignKey("VehicleDetailId")
                        .HasConstraintName("FK_INVOICE_DRIVER");

                    b.HasOne("Invoice.Model.VehicleDetail", "VehicleDetail")
                        .WithMany("Invoices")
                        .HasForeignKey("VehicleDetailId")
                        .HasConstraintName("FK_INVOICE_VEHICLE_DETAIL");

                    b.Navigation("Driver");

                    b.Navigation("FinancialYear");

                    b.Navigation("VehicleDetail");
                });

            modelBuilder.Entity("Invoice.Model.InvoiceDetail", b =>
                {
                    b.HasOne("Invoice.Model.Invoice", null)
                        .WithMany("InvoiceDetail")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("Invoice.Model.ItemMaster", "Item")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_DETAIL_ITEM");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Invoice.Model.ItemMaster", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Items")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ITEM_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.Vehicle", b =>
                {
                    b.HasOne("Invoice.Model.Company", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_COMPANY");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Invoice.Model.VehicleDetail", b =>
                {
                    b.HasOne("Invoice.Model.Vehicle", "Vehicle")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_DETAIL_VEHICLE");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Invoice.Model.VehicleRateConfiguration", b =>
                {
                    b.HasOne("Invoice.Model.ItemMaster", "ItemMaster")
                        .WithMany("VehicleRates")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_RATES_ITEM_DETAIL");

                    b.HasOne("Invoice.Model.Vehicle", "Vehicle")
                        .WithMany("VehicleRates")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_RATES_VEHICLE_DETAIL");

                    b.Navigation("ItemMaster");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Invoice.Model.Bank", b =>
                {
                    b.Navigation("BankDetail");
                });

            modelBuilder.Entity("Invoice.Model.Company", b =>
                {
                    b.Navigation("Banks");

                    b.Navigation("Customers");

                    b.Navigation("Drivers");

                    b.Navigation("FinancialYears");

                    b.Navigation("Items");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Invoice.Model.Driver", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Invoice.Model.FinancialYear", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Invoice.Model.Invoice", b =>
                {
                    b.Navigation("InvoiceDetail");
                });

            modelBuilder.Entity("Invoice.Model.ItemMaster", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("VehicleRates");
                });

            modelBuilder.Entity("Invoice.Model.Vehicle", b =>
                {
                    b.Navigation("VehicleRates");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Invoice.Model.VehicleDetail", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
